/* This file was automatically generated.  Do not edit! */
#undef INTERFACE
void video_play(void);
void video_edit_change(int repeat_count);
void video_edit_accept(void);
void video_select_edit(void);
void video_select_next(void);
void video_select_draw_value(void);
void video_select_begin(void);
void str_2digits(char **buf,int n);
void str_2digits_lno(char **buf,int n);
void select_item_fmt_edit_done(const struct select_item *item);
void select_item_fmt_draw_value(const struct select_item *item, int editsub);
void select_item_fmt_edit_sub(const struct select_item *item, int repeat_count);
void select_item_date_edit_done(const struct select_item *item);
void select_item_date_draw_value(const struct select_item *item, int editsub);
void select_item_date_edit_sub(const struct select_item *item, int repeat_count);
void select_item_time_edit_done(const struct select_item *item);
void select_item_time_draw_value(const struct select_item *item, int editsub);
void select_item_time_edit_sub(const struct select_item *item, int repeat_count);
void select_item_int_edit_sub(const struct select_item *item, int repeat_count);
void select_item_tz_edit_done(const struct select_item *item);
void select_item_display_edit_sub(const struct select_item *item, int repeat_count);
void select_item_display_draw_value(const struct select_item *item, int editsub);
void select_item_tz_edit_sub(const struct select_item *item, int repeat_count);
void select_item_int_draw_value(const struct select_item *item, int editsub);
void select_item_deg_edit_done(const struct select_item *item);
void select_item_deg_draw_value(const struct select_item *item, int editsub);
void select_item_deg_edit_sub(const struct select_item *item, int repeat_count);
void select_item_chime_draw_value(const struct select_item *item, int editsub);
void select_item_chime_edit_sub(const struct select_item *item, int repeat_count);
void video_hour_show_time_date(void);
void video_hour_show_current(void);
float phour_get(time_t gmtt, float lat, float lon, int tz, float *outStart, float *outEnd);
void video_hour_begin(void);
void m7219_send_brightness(void);
void input_process(void);
void input_button_flush_all(void);
int input_button_peek(int button, int mask);
int input_button_consume(int button, int mask);
void input_handle_button(int button, bool is_pressed);
int sunrise_sunset(int doy, float lat, float lon, bool rise, int tz, float *outT);
float norm(float L, float interval);
void m7219_send(uint16_t msg);
void rtc_setup(void);
void app_bkpconfig_read(void);
void app_bkpconfig_write(void);
bool app_bkpconfig_exists(void);
void systick_setup(void);
void clock_setup(void);
void gpio_setup(void);
void m7219_show_splash(int idx);
void m7219_setup(void);
