#define BUTTON_COUNT 2

#define BUTTON_SHORT_MINIMUM 1
#define BUTTON_LONG_MINIMUM 6

#define BUTTON_SHORT 1
#define BUTTON_LONG 2
#define BUTTON_REPEAT 16



#define BUTTON_1_PORT GPIOA
#define BUTTON_1_PIN GPIO0
#define BUTTON_1_IS_PRESSED (gpio_get(BUTTON_1_PORT, BUTTON_1_PIN))

#define BUTTON_2_PORT GPIOA
#define BUTTON_2_PIN GPIO6
#define BUTTON_2_IS_PRESSED (gpio_get(BUTTON_2_PORT, BUTTON_2_PIN))

